export default {
  name: 'alliance',
  side: 'light',
  color: {
    background: '#FC2F00',
    primary: '#EDF2EF',
    secondary: '#FC2F00',
    nav_text: '#FFFFFF',
    nav_text_indicator: '#FFFFFF',
    title: '#0C2030',
    subtitle: '#FC2F00',
    link_text: '#FFFFFF',
    text: '#0C2030',
    neon_hue: 195,
    button: '#FFFFFF',
    button_text: '#FFFFFF',
    input: '#FFFFFF',
    input_text: '#FFFFFF',
  },
  font: {
    title: 'Starwars',
    text: 'RobotoBold',
    simple_text: 'RobotoRegular',
  },
};
