export default {
  name: 'jedi',
  side: 'light',
  color: {
    background: '#9d9974',
    primary: '#3C201B',
    secondary: '#75934e',
    nav_text: '#FFFFFF',
    nav_text_indicator: '#FFFFFF ',
    title: '#3C201B',
    subtitle: '#75934e',
    link_text: '#3C201B',
    text: '#DCC6A0',
    neon_hue: 120,
    button: '#3C201B',
    button_text: '#3C201B',
    input: '#3C201B',
    input_text: '#3C201B',
  },
  font: {
    title: 'Starwars',
    text: 'RobotoBold',
    simple_text: 'RobotoRegular',
  },
};
