export const data1 = {
  count: 6,
  next: null,
  previous: null,
  results: [
    {
      url: 'https://swapi.dev/api/films/1/',
      title: 'A New Hope',
      director: 'George Lucas',
      episode_id: 4,
      release_date: '5/24/1977',
    },
    {
      url: 'https://swapi.dev/api/films/2/',
      title: 'The Empire Strikes Back',
      director: 'Irvin Kershner',
      episode_id: 5,
      release_date: '5/16/1980',
    },
    {
      url: 'https://swapi.dev/api/films/3/',
      title: 'Return of the Jedi',
      director: 'Richard Marquand',
      episode_id: 6,
      release_date: '5/24/1983',
    },
    {
      url: 'https://swapi.dev/api/films/4/',
      title: 'The Phantom Menace',
      director: 'George Lucas',
      episode_id: 1,
      release_date: '5/18/1999',
    },
    {
      url: 'https://swapi.dev/api/films/5/',
      title: 'Attack of the Clones',
      director: 'George Lucas',
      episode_id: 2,
      release_date: '5/15/2002',
    },
    {
      url: 'https://swapi.dev/api/films/6/',
      title: 'Revenge of the Sith',
      director: 'George Lucas',
      episode_id: 3,
      release_date: '5/18/2005',
    },
    {
      url: 'https://swapi.dev/api/films/1/',
      title: 'A New Hope',
      director: 'George Lucas',
      episode_id: 4,
      release_date: '5/24/1977',
    },
    {
      url: 'https://swapi.dev/api/films/2/',
      title: 'The Empire Strikes Back',
      director: 'Irvin Kershner',
      episode_id: 5,
      release_date: '5/16/1980',
    },
    {
      url: 'https://swapi.dev/api/films/3/',
      title: 'Return of the Jedi',
      director: 'Richard Marquand',
      episode_id: 6,
      release_date: '5/24/1983',
    },
    {
      url: 'https://swapi.dev/api/films/4/',
      title: 'The Phantom Menace',
      director: 'George Lucas',
      episode_id: 1,
      release_date: '5/18/1999',
    },
    {
      url: 'https://swapi.dev/api/films/5/',
      title: 'Attack of the Clones',
      director: 'George Lucas',
      episode_id: 2,
      release_date: '5/15/2002',
    },
    {
      url: 'https://swapi.dev/api/films/6/',
      title: 'Revenge of the Sith',
      director: 'George Lucas',
      episode_id: 3,
      release_date: '5/18/2005',
    },
  ],
};

export const planets = {
  count: 60,
  next: 'https://swapi.dev/api/planets/?page=2',
  previous: null,
  results: [
    {
      url: 'https://swapi.dev/api/planets/1/',
      name: 'Tatooine',
      rotation_period: '23',
      orbital_period: '304',
      diameter: '10.465 Km',
      population: '200.000',
    },
    {
      url: 'https://swapi.dev/api/planets/2/',
      name: 'Alderaan',
      rotation_period: '24',
      orbital_period: '364',
      diameter: '12.5 Km',
      population: '2.000.000.000',
    },
    {
      url: 'https://swapi.dev/api/planets/3/',
      name: 'Yavin IV',
      rotation_period: '24',
      orbital_period: '4818',
      diameter: '10.2 Km',
      population: '1.000',
    },
    {
      url: 'https://swapi.dev/api/planets/4/',
      name: 'Hoth',
      rotation_period: '23',
      orbital_period: '549',
      diameter: '7.2 Km',
      population: 'Unknown',
    },
    {
      url: 'https://swapi.dev/api/planets/5/',
      name: 'Dagobah',
      rotation_period: '23',
      orbital_period: '341',
      diameter: '8.9 Km',
      population: 'Unknown',
    },
    {
      url: 'https://swapi.dev/api/planets/6/',
      name: 'Bespin',
      rotation_period: '12',
      orbital_period: '5110',
      diameter: '118 Km',
      population: '6.000.000',
    },
    {
      url: 'https://swapi.dev/api/planets/7/',
      name: 'Endor',
      rotation_period: '18',
      orbital_period: '402',
      diameter: '4.9 Km',
      population: '30.000.000',
    },
    {
      url: 'https://swapi.dev/api/planets/8/',
      name: 'Naboo',
      rotation_period: '26',
      orbital_period: '312',
      diameter: '12.12 Km',
      population: '4.500.000.000',
    },
    {
      url: 'https://swapi.dev/api/planets/9/',
      name: 'Coruscant',
      rotation_period: '24',
      orbital_period: '368',
      diameter: '12.24 Km',
      population: '1.000.000.000.000',
    },
    {
      url: 'https://swapi.dev/api/planets/10/',
      name: 'Kamino',
      rotation_period: '27',
      orbital_period: '463',
      diameter: '19.72 Km',
      population: '1.000.000.000',
    },
  ],
};

export const datax = {
  count: 36,
  next: 'https://swapi.dev/api/starships/?page=2',
  previous: null,
  results: [
    {
      url: 'https://swapi.dev/api/starships/2/',
      name: 'CR90 corvette',
      model: 'CR90 corvette',
      cost_in_credits: '3.500.000',
      hyperdrive_rating: '2.0',
      length: '150 m',
    },
    {
      url: 'https://swapi.dev/api/starships/3/',
      name: 'Star Destroyer',
      model: 'Imperial I-class Star Destroyer',
      cost_in_credits: '150.000.000',
      hyperdrive_rating: '2.0',
      length: '1 m',
    },
    {
      url: 'https://swapi.dev/api/starships/5/',
      name: 'Sentinel-class landing craft',
      model: 'Sentinel-class landing craft',
      cost_in_credits: '240.000',
      hyperdrive_rating: '1.0',
      length: '38 m',
    },
    {
      url: 'https://swapi.dev/api/starships/9/',
      name: 'Death Star',
      model: 'DS-1 Orbital Battle Station',
      cost_in_credits: '1.000.000.000.000',
      hyperdrive_rating: '4.0',
      length: '120.000 m',
    },
    {
      url: 'https://swapi.dev/api/starships/10/',
      name: 'Millennium Falcon',
      model: 'YT-1300 light freighter',
      cost_in_credits: '100.000',
      hyperdrive_rating: '0.5',
      length: '34 m',
    },
    {
      url: 'https://swapi.dev/api/starships/11/',
      name: 'Y-wing',
      model: 'BTL Y-wing',
      cost_in_credits: '134.999',
      hyperdrive_rating: '1.0',
      length: '14 m',
    },
    {
      url: 'https://swapi.dev/api/starships/12/',
      name: 'X-wing',
      model: 'T-65 X-wing',
      cost_in_credits: '149.999',
      hyperdrive_rating: '1.0',
      length: '12 m',
    },
    {
      url: 'https://swapi.dev/api/starships/13/',
      name: 'TIE Advanced x1',
      model: 'Twin Ion Engine Advanced x1',
      cost_in_credits: 'Unknown',
      hyperdrive_rating: '1.0',
      length: '9 m',
    },
    {
      url: 'https://swapi.dev/api/starships/15/',
      name: 'Executor',
      model: 'Executor-class star dreadnought',
      cost_in_credits: '1.143.350.000',
      hyperdrive_rating: '2.0',
      length: '19.000 m',
    },
    {
      url: 'https://swapi.dev/api/starships/17/',
      name: 'Rebel transport',
      model: 'GR-75 medium transport',
      cost_in_credits: 'Unknown',
      hyperdrive_rating: '4.0',
      length: '90 m',
    },
  ],
};

export const data = {
  url: 'https://swapi.dev/api/planets/3/',
  name: 'Yavin IV',
  climate: 'temperate, tropical',
  gravity: '1 standard',
  terrain: 'jungle, rainforests',
  surface_water: '8',
  orbital_period: '4818',
  rotation_period: '24',
  diameter: '10.2 Km',
  population: '1.000',
  edited: '20/12/2014 - 18:58:18',
  created: '10/12/2014 - 09:37:19',
  films: [
    {
      title: 'A New Hope',
      url: 'https://swapi.dev/api/films/1/',
    },
  ],
  residents: [],
};

export const isLoading = false;
